In [26]:
import pandas as pd
import numpy as np
import seaborn as sns

In [61]:
# Import cities file as DataFrame

dict_pd = pd.read_csv("C:/Users/HP 13-AD004LA/Desktop/MBA/Columbia Engineering/Project/Project 2/data/dictionary.csv")
summer_pd = pd.read_csv("C:/Users/HP 13-AD004LA/Desktop/MBA/Columbia Engineering/Project/Project 2/data/summer.csv")
winter_pd = pd.read_csv("C:/Users/HP 13-AD004LA/Desktop/MBA/Columbia Engineering/Project/Project 2/data/winter.csv")
GDP_pd = pd.read_csv("C:/Users/HP 13-AD004LA/Desktop/MBA/Columbia Engineering/Project/Project 2/data/GDP_T.csv")
ath_pd = pd.read_csv("C:/Users/HP 13-AD004LA/Desktop/MBA/Columbia Engineering/Project/Project 2/data/athletes.csv")
dict2_pd = pd.read_csv("C:/Users/HP 13-AD004LA/Desktop/MBA/Columbia Engineering/Project/Project 2/data/dictionary_2.csv")
#"../Resources/cities.csv"

In [63]:
ath_df = pd.merge(dict2_pd,ath_pd, how = 'inner',on = 'NOC')

In [107]:
pd.options.display.float_format = '{:,.1f}'.format
x = ath_df.groupby('region')['Age','Height','Weight'].mean()
x.sort_values(['Age','Height', 'Weight'], axis=0, ascending=True, inplace=True)

In [112]:
y = pd.DataFrame(ath_df.groupby('region')['Medal'].count())
y.sort_values(["Medal"], axis=0, ascending=True, inplace=True) 
y.head(150)

                                  Medal
region
Liberia                               0
Palestine                             0
Papua New Guinea                      0
Republic of Congo                     0
Rwanda                                0
Equatorial Guinea                     0
El Salvador                           0
Saint Kitts                           0
Palau                                 0
Saint Lucia                           0
Dominica                              0
Samoa                                 0
Democratic Republic of the Congo      0
Lesotho                               0
Sao Tome and Principe                 0
Seychelles                            0
Cook Islands                          0
Saint Vincent                         0
Comoros                               0
Gambia                                0
Nicaragua                             0
Kiribati                              0
Libya                                 0
Madagascar                            0
Malawi                                0
Maldives                              0
Mali                                  0
Malta                                 0
Oman                                  0
Marshall Islands                      0
...                                 ...
Moldova                               8
Puerto Rico                           9
Liechtenstein                         9
Israel                                9
Philippines                          10
Fiji                                 13
Tunisia                              13
Montenegro                           14
Peru                                 15
Venezuela                            15
Armenia                              16
Malaysia                             16
Paraguay                             17
Algeria                              17
Iceland                              17
Cameroon                             22
Zimbabwe                             22
Ghana                                23
Morocco                              23
Mongolia                             26
Egypt                                27
Colombia                             28
Thailand                             30
Chile                                32
Georgia                              32
Uzbekistan                           34
Latvia                               35
Ireland                              35
Trinidad                             37
Bahamas                              40

[150 rows x 1 columns]

In [108]:
x

                         Age  Height  Weight
region
Marshall Islands        20.3   168.5    70.3
Maldives                20.9   163.8    55.0
Saint Vincent           21.5   177.0    66.7
Laos                    21.6   166.4    57.8
Yemen                   21.6   168.2    61.5
Kiribati                21.6   166.9    78.4
Suriname                21.7   171.4    64.9
Niger                   21.9   172.4    64.4
Somalia                 22.0   176.0    64.4
North Korea             22.1   161.6    57.3
Sao Tome and Principe   22.2   172.3    63.5
Comoros                 22.2   170.9    59.9
Honduras                22.3   173.5    69.0
Macedonia               22.3   174.9    68.4
Brunei                  22.3   166.1    66.0
Sierra Leone            22.4   177.0    68.2
Kuwait                  22.6   174.5    73.9
Bangladesh              22.6   166.2    61.3
Seychelles              22.6   175.5    69.9
Palau                   22.7   165.5    67.5
Liberia                 22.8   173.6    65.9
Grenada                 22.8   175.2    67.5
Cook Islands            22.9   171.3    77.3
Equatorial Guinea       22.9   170.3    67.8
Andorra                 23.1   173.7    70.6
South Korea             23.1   172.0    66.8
El Salvador             23.2   169.6    63.1
China                   23.2   172.6    66.2
Mozambique              23.2   172.6    66.1
Chad                    23.2   176.6    65.8
...                      ...     ...     ...
Argentina               25.9   176.6    74.0
Boliva                  26.0   171.3    64.9
Bhutan                  26.0   166.5    60.3
Belize                  26.0   175.1    68.3
USA                     26.1   176.9    72.6
Slovakia                26.1   178.2    73.8
Virgin Islands, British 26.2   178.6    73.8
Bahamas                 26.4   177.4    73.2
Luxembourg              26.4   173.9    70.5
Bermuda                 26.5   177.4    74.1
Tajikistan              26.6   174.6    76.1
Finland                 26.6   175.8    71.1
Curacao                 26.6   177.3    76.2
Netherlands             26.6   179.5    73.6
Latvia                  26.7   179.6    78.3
Switzerland             26.7   175.2    70.7
France                  26.8   175.3    69.6
Norway                  26.8   178.0    72.8
Sweden                  26.8   177.9    73.1
UK                      26.9   175.7    70.9
Austria                 27.0   177.4    73.7
Belgium                 27.0   176.1    70.2
Portugal                27.0   173.5    68.2
Montenegro              27.1   183.6    84.8
American Samoa          27.2   175.7    88.0
Virgin Islands, US      27.3   177.9    73.4
Denmark                 27.4   179.2    73.8
Ireland                 27.5   176.6    70.4
Namibia                 27.9   172.9    63.7
Monaco                  30.0   176.3    77.0

[205 rows x 3 columns]